name: Build ReviANGLE

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure CMake
        run: cmake -B build -A x64 -DREVIANGLE_BACKEND_D3D11=OFF -DREVIANGLE_BACKEND_VULKAN=ON

      - name: Build
        run: cmake --build build --config Release --target opengl32

      - name: Upload ReviANGLE DLL
        uses: actions/upload-artifact@v4
        with:
          name: ReviANGLE-Vulkan-patched
          path: build/dll/opengl32.dll
